### ISSUE TITLE
inline-block width incorrect

### ISSUE THREAD

**Issue by DrParanoia** [stefanhaustein/htmlview#6]
So if i set `display: inline-block` the width of this element becomes zero :/ Are there any plans to improve this library? It's really awesome!

**Comment by stefanhaustein** [comment]
Would you mind creating a test case that reproduces this?

**Comment by DrParanoia** [comment]
Wow! Didn't expect such a fast response!

Sure! What I am trying to do, is to achieve a `text-align: super` effect. But since it is not supported, I am trying to use an `inline-block` and fix everything with padding:

    <style>
        table {
            font-size: 30px;
        }
        td {
            width: 50%;
            font-size: 30px;
            text-align: center;
            vertical-align: middle;
        }
        .super {
            font-size: 20px;
            display: inline-block;
        }
    </style>

    <table>
        <tr>
            <th>Price</th>
            <th>Our price</th>
        </tr>
        <tr>
            <td>
                <span>14</span>
                <span class="super">00</span>
            </td>
            <td>
                <span>9</span>
                <span class="super">99</span>
            </td>
        </tr>
    </table>

I think the table may be causing the problem though.

**Comment by stefanhaustein** [comment]
I must admit I had thought of some kind of roboelectric test (I am aware there aren't any yet)

**Comment by DrParanoia** [comment]
Oh :D So is there any hope? This library is awesome to use in a ListView since it loads pretty fast!

**Comment by stefanhaustein** [comment]
text-align: super / sub might be relatively straightforward to implement in LayoutContext.getAdjustmentY... I'll take a look...

**Comment by stefanhaustein** [comment]
Ok, sub/sup elements should work now.
Note that I have changed the project layout to what AS expects in a previous commit. 
Do you know if the inline-block width problem is limited to tables?
